- name: Bulid nginx Image
  docker_image:
    name: nginx
    source: build
    build:
      path: /root/Dockerfiles/nginx
      args:
        HOST: "{{host_domain}}"

- name: Run nginx Container
  docker_container:
    name: nginx
    image: nginx
    restart: yes
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - wp:/var/www/wordpress
      - pma:/var/www/phpmyadmin
    networks:
      - name: local_network
        ipv4_address: "192.0.69.5"