- name: Set Up Docker Prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker's GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: yes

- name: Install pip3
  apt:
    name: 
    - python3
    - python3-pip
    update_cache: yes

- name: Install Python's Docker Module
  pip:
    name:
      - docker
      - docker-compose
    state: present

- name: Copy Dockerfiles
  copy:
    src: ./Dockerfiles
    dest: /root
    owner: root
    group: root
    mode: '0755'